import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/appsidebar";
import { ThemeProvider } from "@/components/providers/themeprovider";
import Footer from "@/components/footer";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="bg-gray-100 dark:bg-[#262626] w-full h-full ">
            <SidebarProvider>
              <main>
                <AppSidebar />
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
